server:
  servlet:
    context-path: /api/v1

spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        '[format_sql]': true
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/ctpacolhe?serverTimezone=UTC}
    username: ${MYSQLUSER:root}
    password: ${MYSQLPASSWORD:123456}
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    test-connection: false
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        debug: true
        smtps:
          localhost: 'localhost'
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enabled: true

support:
  mail: ${SUPPORT_EMAIL:lotusteam.2023@gmail.com}
  name: ${SUPPORT_NAME:CTP Acolhe | Lotus}

frontend:
  url: ${FRONTEND_URL:http://localhost:5173}
  
account:
  verification-token-expires-in: 1800
  password-reset-token-expires-in: 1800
  
jwt:
  secret: ${JWT_SECRET:asdfSFS34wfsdfsdfSDSD32dfsddDDerQSNCK34SOWEK5354fdgdf4}
  access-token-expires-in: ${JWT_ACCESS_TOKEN_EXPIRES_IN:7200}
  refresh-token-expires-in: ${JWT_REFRESH_TOKEN_EXPIRES_IN:86400}

logging:
  level:
    '[org.hibernate.SQL]': DEBUG
    '[org.hibernate.type.descriptor.sql.BasicBinder]': TRACE
    '[org.hibernate.type]': TRACE