server:
  servlet:
    context-path: /api/v1

spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  datasource:
    url: jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}:/${MYSQLDATABASE};
    username: ${MYSQLUSER}
    password: ${MYSQLPASSWORD}
    name: ctpacolhe

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type: TRACE