package br.edu.ifsp.spo.ctpacolhe.common.email;

public class TemplateEmailDefault {
	public static String getContent() {
		return "<html>\r\n"
				+ "<head>\r\n"
				+ "  <title></title>\r\n"
				+ "  <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n"
				+ "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
				+ "  <link href=\"https://fonts.googleapis.com/css?family=Poppins\" rel=\"stylesheet\" type=\"text/css\">\r\n"
				+ "  <style>\r\n"
				+ "    * {\r\n"
				+ "      box-sizing: border-box;\r\n"
				+ "    }\r\n"
				+ "\r\n"
				+ "    body {\r\n"
				+ "      margin: 0;\r\n"
				+ "      padding: 0;\r\n"
				+ "    }\r\n"
				+ "\r\n"
				+ "    a[x-apple-data-detectors] {\r\n"
				+ "      color: inherit !important;\r\n"
				+ "      text-decoration: inherit !important;\r\n"
				+ "    }\r\n"
				+ "\r\n"
				+ "    #MessageViewBody a {\r\n"
				+ "      color: inherit;\r\n"
				+ "      text-decoration: none;\r\n"
				+ "    }\r\n"
				+ "\r\n"
				+ "    p {\r\n"
				+ "      line-height: inherit\r\n"
				+ "    }\r\n"
				+ "\r\n"
				+ "    .desktop_hide,\r\n"
				+ "    .desktop_hide table {\r\n"
				+ "      mso-hide: all;\r\n"
				+ "      display: none;\r\n"
				+ "      max-height: 0px;\r\n"
				+ "      overflow: hidden;\r\n"
				+ "    }\r\n"
				+ "\r\n"
				+ "    .image_block img+div {\r\n"
				+ "      display: none;\r\n"
				+ "    }\r\n"
				+ "\r\n"
				+ "    @media (max-width:700px) {\r\n"
				+ "      .desktop_hide table.icons-inner {\r\n"
				+ "        display: inline-block !important;\r\n"
				+ "      }\r\n"
				+ "\r\n"
				+ "      .icons-inner {\r\n"
				+ "        text-align: center;\r\n"
				+ "      }\r\n"
				+ "\r\n"
				+ "      .icons-inner td {\r\n"
				+ "        margin: 0 auto;\r\n"
				+ "      }\r\n"
				+ "\r\n"
				+ "      .fullMobileWidth,\r\n"
				+ "      .row-content {\r\n"
				+ "        width: 100% !important;\r\n"
				+ "      }\r\n"
				+ "\r\n"
				+ "      .mobile_hide {\r\n"
				+ "        display: none;\r\n"
				+ "      }\r\n"
				+ "\r\n"
				+ "      .stack .column {\r\n"
				+ "        width: 100%;\r\n"
				+ "        display: block;\r\n"
				+ "      }\r\n"
				+ "\r\n"
				+ "      .mobile_hide {\r\n"
				+ "        min-height: 0;\r\n"
				+ "        max-height: 0;\r\n"
				+ "        max-width: 0;\r\n"
				+ "        overflow: hidden;\r\n"
				+ "        font-size: 0px;\r\n"
				+ "      }\r\n"
				+ "\r\n"
				+ "      .desktop_hide,\r\n"
				+ "      .desktop_hide table {\r\n"
				+ "        display: table !important;\r\n"
				+ "        max-height: none !important;\r\n"
				+ "      }\r\n"
				+ "\r\n"
				+ "      .row-4 .column-1 .block-1.paragraph_block td.pad {\r\n"
				+ "        padding: 5px 30px !important;\r\n"
				+ "      }\r\n"
				+ "\r\n"
				+ "      .row-3 .column-1 .block-2.heading_block td.pad {\r\n"
				+ "        padding: 10px 60px 30px !important;\r\n"
				+ "      }\r\n"
				+ "\r\n"
				+ "      .row-3 .column-1 .block-2.heading_block h1 {\r\n"
				+ "        font-size: 33px !important;\r\n"
				+ "      }\r\n"
				+ "\r\n"
				+ "      .row-8 .column-1 .block-1.heading_block h2 {\r\n"
				+ "        font-size: 16px !important;\r\n"
				+ "      }\r\n"
				+ "    }\r\n"
				+ "  </style>\r\n"
				+ "</head>\r\n"
				+ "<body style=\"margin: 0; background-color: #eaeaea; padding: 0; -webkit-text-size-adjust: none; text-size-adjust: none;\">\r\n"
				+ "  <table class=\"nl-container\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\"\r\n"
				+ "    style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #eaeaea;\">\r\n"
				+ "    <tbody>\r\n"
				+ "      <tr>\r\n"
				+ "        <td>\r\n"
				+ "          <table class=\"row row-1\" align=\"center\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\r\n"
				+ "            role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
				+ "            <tbody>\r\n"
				+ "              <tr>\r\n"
				+ "                <td>\r\n"
				+ "                  <table class=\"row-content\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\r\n"
				+ "                    role=\"presentation\"\r\n"
				+ "                    style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #eaeaea; color: #000000; width: 680px;\"\r\n"
				+ "                    width=\"680\">\r\n"
				+ "                    <tbody>\r\n"
				+ "                      <tr>\r\n"
				+ "                        <td class=\"column column-1\" width=\"100%\"\r\n"
				+ "                          style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; padding-bottom: 10px; padding-top: 20px; vertical-align: top; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;\">\r\n"
				+ "                          <table class=\"icons_block block-1\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\r\n"
				+ "                            role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
				+ "                            <tr>\r\n"
				+ "                              <td class=\"pad\"\r\n"
				+ "                                style=\"vertical-align: middle; color: #000000; font-family: inherit; font-size: 14px; text-align: center;\">\r\n"
				+ "                                <table class=\"alignment\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\"\r\n"
				+ "                                  align=\"center\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
				+ "                                  <tr>\r\n"
				+ "                                    <td\r\n"
				+ "                                      style=\"vertical-align: middle; text-align: center; padding-top: 20px; padding-bottom: 20px; padding-left: 20px; padding-right: 20px;\">\r\n"
				+ "                                      <img class=\"icon\"\r\n"
				+ "                                        src=\"https://media.discordapp.net/attachments/1077345452694970438/1099690236369444924/Logo_1.png?width=1025&height=399\"\r\n"
				+ "                                        height=\"64\" width=\"156\" align=\"center\"\r\n"
				+ "                                        style=\"display: block; height: auto; margin: 0 auto; border: 0;\"></td>\r\n"
				+ "                                  </tr>\r\n"
				+ "                                </table>\r\n"
				+ "                              </td>\r\n"
				+ "                            </tr>\r\n"
				+ "                          </table>\r\n"
				+ "                        </td>\r\n"
				+ "                      </tr>\r\n"
				+ "                    </tbody>\r\n"
				+ "                  </table>\r\n"
				+ "                </td>\r\n"
				+ "              </tr>\r\n"
				+ "            </tbody>\r\n"
				+ "          </table>\r\n"
				+ "          <table class=\"row row-2\" align=\"center\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\r\n"
				+ "            role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-size: auto;\">\r\n"
				+ "            <tbody>\r\n"
				+ "              <tr>\r\n"
				+ "                <td>\r\n"
				+ "                  <table class=\"row-content stack\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\r\n"
				+ "                    role=\"presentation\"\r\n"
				+ "                    style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-size: auto; background-color: #ffffff; color: #000000; border-bottom: 0 solid #FFFFFF; border-left: 0 solid #FFFFFF; border-radius: 30px 30px 0 0; border-right: 0px solid #FFFFFF; border-top: 0 solid #FFFFFF; width: 680px;\"\r\n"
				+ "                    width=\"680\">\r\n"
				+ "                    <tbody>\r\n"
				+ "                      <tr>\r\n"
				+ "                        <td class=\"column column-1\" width=\"100%\"\r\n"
				+ "                          style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; vertical-align: top; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;\">\r\n"
				+ "                        </td>\r\n"
				+ "                      </tr>\r\n"
				+ "                    </tbody>\r\n"
				+ "                  </table>\r\n"
				+ "                </td>\r\n"
				+ "              </tr>\r\n"
				+ "            </tbody>\r\n"
				+ "          </table>\r\n"
				+ "          <table class=\"row row-3\" align=\"center\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\r\n"
				+ "            role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
				+ "            <tbody>\r\n"
				+ "              <tr>\r\n"
				+ "                <td>\r\n"
				+ "                  <table class=\"row-content stack\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\r\n"
				+ "                    role=\"presentation\"\r\n"
				+ "                    style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #ffffff; color: #000000; width: 680px;\"\r\n"
				+ "                    width=\"680\">\r\n"
				+ "                    <tbody>\r\n"
				+ "                      <tr>\r\n"
				+ "                        <td class=\"column column-1\" width=\"100%\"\r\n"
				+ "                          style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; vertical-align: top; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;\">\r\n"
				+ "                          <table class=\"image_block block-1\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\r\n"
				+ "                            role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
				+ "                            <tr>\r\n"
				+ "                              <td class=\"pad\" style=\"width:100%;padding-right:0px;padding-left:0px;\">\r\n"
				+ "                                <div class=\"alignment\" align=\"center\" style=\"line-height:10px\"><img\r\n"
				+ "                                    class=\"fullMobileWidth\"\r\n"
				+ "                                    src=\"https://cdn.discordapp.com/attachments/1077345452694970438/1114708820510388284/image_33.png\"\r\n"
				+ "                                    style=\"display: block; height: auto; border: 0; width: 442px; max-width: 100%;\"\r\n"
				+ "                                    width=\"442\" alt=\"Social profile\" title=\"Social profile\"></div>\r\n"
				+ "                              </td>\r\n"
				+ "                            </tr>\r\n"
				+ "                          </table>\r\n"
				+ "                          <table class=\"heading_block block-2\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\r\n"
				+ "                            role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
				+ "                            <tr>\r\n"
				+ "                              <td class=\"pad\"\r\n"
				+ "                                style=\"padding-bottom:20px;padding-left:60px;padding-right:60px;padding-top:10px;text-align:center;width:100%;\">\r\n"
				+ "                                <h1\r\n"
				+ "                                  style=\"margin: 0; color: #020b22; direction: ltr; font-family: Poppins, Arial, Helvetica, sans-serif; font-size: 40px; font-weight: 700; letter-spacing: normal; line-height: 150%; text-align: center; margin-top: 0; margin-bottom: 0;\">\r\n"
				+ "                                  <span class=\"tinyMce-placeholder\">{{TITULO}}</span></h1>\r\n"
				+ "                              </td>\r\n"
				+ "                            </tr>\r\n"
				+ "                          </table>\r\n"
				+ "                        </td>\r\n"
				+ "                      </tr>\r\n"
				+ "                    </tbody>\r\n"
				+ "                  </table>\r\n"
				+ "                </td>\r\n"
				+ "              </tr>\r\n"
				+ "            </tbody>\r\n"
				+ "          </table>\r\n"
				+ "          <table class=\"row row-4\" align=\"center\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\r\n"
				+ "            role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
				+ "            <tbody>\r\n"
				+ "              <tr>\r\n"
				+ "                <td>\r\n"
				+ "                  <table class=\"row-content stack\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\r\n"
				+ "                    role=\"presentation\"\r\n"
				+ "                    style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #ffffff; color: #000000; width: 680px;\"\r\n"
				+ "                    width=\"680\">\r\n"
				+ "                    <tbody>\r\n"
				+ "                      <tr>\r\n"
				+ "                        <td class=\"column column-1\" width=\"100%\"\r\n"
				+ "                          style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; padding-bottom: 60px; vertical-align: top; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px; padding-bottom: 0px;\">\r\n"
				+ "                          <table class=\"paragraph_block block-1\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\r\n"
				+ "                            role=\"presentation\"\r\n"
				+ "                            style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;\">\r\n"
				+ "                            <tr>\r\n"
				+ "                              <td class=\"pad\"\r\n"
				+ "                                style=\"padding-bottom:5px;padding-left:60px;padding-right:60px;padding-top:5px;\">\r\n"
				+ "                                <div\r\n"
				+ "                                  style=\"color:#878787;direction:ltr;font-family:Poppins, Arial, Helvetica, sans-serif;font-size:16px;font-weight:400;letter-spacing:0px;line-height:120%;text-align:center;mso-line-height-alt:19.2px;\">\r\n"
				+ "                                  <p style=\"margin: 0; margin-bottom: 16px;\">Olá, {{NOME}}.</p>\r\n"
				+ "                                  <p style=\"margin: 0; margin-bottom: 16px;\">{{PARAGRAFO}}</p>\r\n"
				+ "                                  <p style=\"margin: 0;\">{{ACAO}}</p>\r\n"
				+ "                                </div>\r\n"
				+ "                              </td>\r\n"
				+ "                            </tr>\r\n"
				+ "                          </table>\r\n"
				+ "                          <table class=\"button_block block-3\" width=\"100%\" border=\"0\" cellpadding=\"10\" cellspacing=\"0\"\r\n"
				+ "                            role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
				+ "                            <tr>\r\n"
				+ "                              <td class=\"pad\" style=\"padding-top: 25px; padding-bottom: 15px;\">\r\n"
				+ "                                <div class=\"alignment\" align=\"center\">\r\n"
				+ "                                  <a href=\"{{URL_LINK}}\"\r\n"
				+ "                                    style=\"text-decoration:none;display:inline-block;color:#ffffff;background-color:#2b2b2b;border-radius:16px;width:auto;border-top:0px solid transparent;font-weight:400;border-right:0px solid transparent;border-bottom:0px solid transparent;border-left:0px solid transparent;padding-top:5px;padding-bottom:5px;font-family:Poppins, Arial, Helvetica, sans-serif;font-size:24px;text-align:center;mso-border-alt:none;word-break:keep-all;\"><span\r\n"
				+ "                                      style=\"padding-left:20px;padding-right:20px;font-size:24px;display:inline-block;letter-spacing:normal;\"><span\r\n"
				+ "                                        dir=\"ltr\" style=\"word-break: break-word; line-height: 48px;\">{{TITULO_BOTAO}}</span></span></a>\r\n"
				+ "                                </div>\r\n"
				+ "                              </td>\r\n"
				+ "                            </tr>\r\n"
				+ "                          </table>\r\n"
				+ "                        </td>\r\n"
				+ "                      </tr>\r\n"
				+ "                    </tbody>\r\n"
				+ "                  </table>\r\n"
				+ "                </td>\r\n"
				+ "              </tr>\r\n"
				+ "            </tbody>\r\n"
				+ "          </table>\r\n"
				+ "          <table class=\"row row-5\" align=\"center\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\r\n"
				+ "            role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
				+ "            <tbody>\r\n"
				+ "              <tr>\r\n"
				+ "                <td>\r\n"
				+ "                  <table class=\"row-content stack\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\r\n"
				+ "                    role=\"presentation\"\r\n"
				+ "                    style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #ffffff; color: #000000; width: 680px;\"\r\n"
				+ "                    width=\"680\">\r\n"
				+ "                    <tbody>\r\n"
				+ "                      <tr>\r\n"
				+ "                        <td class=\"column column-1\" width=\"100%\"\r\n"
				+ "                          style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; padding-bottom: 5px; padding-top: 5px; vertical-align: top; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;\">\r\n"
				+ "                          <table class=\"text_block block-1\" width=\"100%\" border=\"0\" cellpadding=\"10\" cellspacing=\"0\"\r\n"
				+ "                            role=\"presentation\"\r\n"
				+ "                            style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;\">\r\n"
				+ "                            <tr>\r\n"
				+ "                              <td class=\"pad\">\r\n"
				+ "                                <div style=\"font-family: sans-serif\">\r\n"
				+ "                                  <div class\r\n"
				+ "                                    style=\"font-size: 12px; font-family: Poppins, Arial, Helvetica, sans-serif; mso-line-height-alt: 14.399999999999999px; line-height: 1.2;\">\r\n"
				+ "                                    <p\r\n"
				+ "                                      style=\"margin: 0; font-size: 14px; text-align: center; mso-line-height-alt: 16.8px;\">\r\n"
				+ "                                      Caso não consiga utilizar o botão, copie e cole o seguinte link no seu navegador:\r\n"
				+ "                                    </p>\r\n"
				+ "                                    <p\r\n"
				+ "                                      style=\"margin: 0; font-size: 14px; text-align: center; mso-line-height-alt: 14.399999999999999px;\">\r\n"
				+ "                                      &nbsp;</p>\r\n"
				+ "                                    <p\r\n"
				+ "                                      style=\"margin: 0 auto; font-size: 14px; text-align: center; mso-line-height-alt: 16.8px;\">\r\n"
				+ "                                      <a href=\"{{URL_LINK}}\" target=\"_blank\">{{URL_LINK}}</a></p>\r\n"
				+ "                                    <p\r\n"
				+ "                                      style=\"margin: 0; font-size: 14px; text-align: center; mso-line-height-alt: 14.399999999999999px;\">\r\n"
				+ "                                      &nbsp;</p>\r\n"
				+ "                                  </div>\r\n"
				+ "                                </div>\r\n"
				+ "                              </td>\r\n"
				+ "                            </tr>\r\n"
				+ "                          </table>\r\n"
				+ "                        </td>\r\n"
				+ "                      </tr>\r\n"
				+ "                    </tbody>\r\n"
				+ "                  </table>\r\n"
				+ "                </td>\r\n"
				+ "              </tr>\r\n"
				+ "            </tbody>\r\n"
				+ "          </table>\r\n"
				+ "          <table class=\"row row-6 mobile_hide\" align=\"center\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\r\n"
				+ "            role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
				+ "            <tbody>\r\n"
				+ "              <tr>\r\n"
				+ "                <td>\r\n"
				+ "                  <table class=\"row-content stack\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\r\n"
				+ "                    role=\"presentation\"\r\n"
				+ "                    style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #2b2b2b; color: #000000; width: 680px;\"\r\n"
				+ "                    width=\"680\">\r\n"
				+ "                    <tbody>\r\n"
				+ "                      <tr>\r\n"
				+ "                        <td class=\"column column-1\" width=\"100%\"\r\n"
				+ "                          style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; padding-left: 50px; padding-right: 50px; padding-top: 15px; vertical-align: top; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;\">\r\n"
				+ "                          <table class=\"text_block block-1\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\r\n"
				+ "                            role=\"presentation\"\r\n"
				+ "                            style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;\">\r\n"
				+ "                            <tr>\r\n"
				+ "                              <td class=\"pad\" style=\"padding-bottom:5px; padding-top:10px;\">\r\n"
				+ "                                <div style=\"font-family: sans-serif\">\r\n"
				+ "                                  <div class\r\n"
				+ "                                    style=\"font-size: 12px; font-family: Poppins, Arial, Helvetica, sans-serif; mso-line-height-alt: 14.399999999999999px; color: #eaeaea; line-height: 1.2;\">\r\n"
				+ "                                    <p\r\n"
				+ "                                      style=\"margin: 0; font-size: 14px; text-align: center; mso-line-height-alt: 16.8px;\">\r\n"
				+ "                                      <span style=\"font-size:16px;\">Para mais informações, acesse o link abaixo:</span>\r\n"
				+ "                                    </p>\r\n"
				+ "                                  </div>\r\n"
				+ "                                </div>\r\n"
				+ "                              </td>\r\n"
				+ "                            </tr>\r\n"
				+ "                          </table>\r\n"
				+ "                        </td>\r\n"
				+ "                      </tr>\r\n"
				+ "                    </tbody>\r\n"
				+ "                  </table>\r\n"
				+ "                </td>\r\n"
				+ "              </tr>\r\n"
				+ "            </tbody>\r\n"
				+ "          </table>\r\n"
				+ "          <table class=\"row row-7\" align=\"center\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\r\n"
				+ "            role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
				+ "            <tbody>\r\n"
				+ "              <tr>\r\n"
				+ "                <td>\r\n"
				+ "                  <table class=\"row-content stack\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\r\n"
				+ "                    role=\"presentation\"\r\n"
				+ "                    style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #ffffff; color: #000000; width: 680px; border-radius: 0 0 30px 30px;\"\r\n"
				+ "                    width=\"680\">\r\n"
				+ "                    <tbody>\r\n"
				+ "                      <tr>\r\n"
				+ "                        <td class=\"column column-1\" width=\"50%\"\r\n"
				+ "                          style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; background-color: #2b2b2b; padding-bottom: 5px; padding-top: 5px; vertical-align: top; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px; border-radius: 0 0 30px 30px;\">\r\n"
				+ "                          <table class=\"icons_block block-1\" width=\"100%\" border=\"0\" cellpadding=\"20\" cellspacing=\"0\"\r\n"
				+ "                            role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
				+ "                            <tr>\r\n"
				+ "                              <td class=\"pad\" style=\"vertical-align: middle; padding-top: 0px;\">\r\n"
				+ "                                <table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\"\r\n"
				+ "                                  style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
				+ "                                  <tr>\r\n"
				+ "                                    <td class=\"alignment\" style=\"vertical-align: middle; text-align: center;\">\r\n"
				+ "                                      <table class=\"icons-inner\"\r\n"
				+ "                                        style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; display: inline-block; margin-right: -4px; padding-left: 0px; padding-right: 0px;\"\r\n"
				+ "                                        cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\">\r\n"
				+ "                                        <tr>\r\n"
				+ "                                          <td\r\n"
				+ "                                            style=\"vertical-align: middle; text-align: center; padding-bottom: 15px; padding-left: 10px; padding-right: 10px;\">\r\n"
				+ "                                            <a href=\"https://spo.ifsp.edu.br/sociopedagógico\" target=\"_blank\"\r\n"
				+ "                                              style=\"text-decoration: none;\"><img class=\"icon\" alt=\"Blog\"\r\n"
				+ "                                                src=\"https://cdn.discordapp.com/attachments/1077345452694970438/1114712731623362632/Marca_IFSP_2015_SaoPaulo-07-removebg-preview.png\"\r\n"
				+ "                                                width=\"252\" align=\"center\"\r\n"
				+ "                                                style=\"display: block; height: auto; margin: 0 auto; border: 0;\"></a>\r\n"
				+ "                                          </td>\r\n"
				+ "                                        </tr>\r\n"
				+ "                                        <tr>\r\n"
				+ "                                          <td\r\n"
				+ "                                            style=\"font-family: Poppins, Arial, Helvetica, sans-serif; font-size: 16px; color: #ffffff; vertical-align: middle; letter-spacing: undefined; text-align: center;\">\r\n"
				+ "                                            <a href=\"https://spo.ifsp.edu.br/sociopedagógico\" target=\"_blank\"\r\n"
				+ "                                              style=\"color: #ffffff; text-decoration: none;\">Coordenadoria\r\n"
				+ "                                              Técnico-Pedagógica</a></td>\r\n"
				+ "                                        </tr>\r\n"
				+ "                                      </table>\r\n"
				+ "                                    </td>\r\n"
				+ "                                  </tr>\r\n"
				+ "                                </table>\r\n"
				+ "                              </td>\r\n"
				+ "                            </tr>\r\n"
				+ "                          </table>\r\n"
				+ "                        </td>\r\n"
				+ "                      </tr>\r\n"
				+ "                    </tbody>\r\n"
				+ "                  </table>\r\n"
				+ "                </td>\r\n"
				+ "              </tr>\r\n"
				+ "            </tbody>\r\n"
				+ "          </table>\r\n"
				+ "          <table class=\"row row-9\" align=\"center\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\r\n"
				+ "            role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
				+ "            <tbody>\r\n"
				+ "              <tr>\r\n"
				+ "                <td>\r\n"
				+ "                  <table class=\"row-content stack\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\r\n"
				+ "                    role=\"presentation\"\r\n"
				+ "                    style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #eaeaea; color: #000000; width: 680px;\"\r\n"
				+ "                    width=\"680\">\r\n"
				+ "                    <tbody>\r\n"
				+ "                      <tr>\r\n"
				+ "                        <td class=\"column column-1\" width=\"100%\"\r\n"
				+ "                          style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; padding-bottom: 10px; padding-top: 10px; vertical-align: top; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;\">\r\n"
				+ "                          <table class=\"text_block block-1\" width=\"100%\" border=\"0\" cellpadding=\"20\" cellspacing=\"0\"\r\n"
				+ "                            role=\"presentation\"\r\n"
				+ "                            style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;\">\r\n"
				+ "                            <tr>\r\n"
				+ "                              <td class=\"pad\">\r\n"
				+ "                                <div style=\"font-family: sans-serif\">\r\n"
				+ "                                  <div class\r\n"
				+ "                                    style=\"font-size: 12px; font-family: Poppins, Arial, Helvetica, sans-serif; mso-line-height-alt: 14.399999999999999px; color: #000000; line-height: 1.2;\">\r\n"
				+ "                                    <p\r\n"
				+ "                                      style=\"margin: 0; font-size: 10px; text-align: center; mso-line-height-alt: 12px;\">\r\n"
				+ "                                      <span style=\"font-size:12px;\"><span style><span style>© 2023 Equipe\r\n"
				+ "                                            Lotus.&nbsp;</span></span><span style><span style> Todos os direitos\r\n"
				+ "                                            reservados.</span></span></span></p>\r\n"
				+ "                                  </div>\r\n"
				+ "                                </div>\r\n"
				+ "                              </td>\r\n"
				+ "                            </tr>\r\n"
				+ "                          </table>\r\n"
				+ "                        </td>\r\n"
				+ "                      </tr>\r\n"
				+ "                    </tbody>\r\n"
				+ "                  </table>\r\n"
				+ "                </td>\r\n"
				+ "              </tr>\r\n"
				+ "            </tbody>\r\n"
				+ "          </table>\r\n"
				+ "        </td>\r\n"
				+ "      </tr>\r\n"
				+ "    </tbody>\r\n"
				+ "  </table>\r\n"
				+ "</body>\r\n"
				+ "</html>";
	}
}
